version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/credenciales.json:/app/credenciales.json:ro
      - ./backend/.env:/app/.env:ro
      - /home/luisazanavega/chroma_db/chroma_db:/app/chroma_db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  pgdata:
